---
- name: Remove and copy fail2ban dingtalk action script
  hosts: bad
  become: yes

  tasks:
    - name : star
      command : sudo fail2ban-client start
    - name: Check fail2ban status
      command: sudo fail2ban-client status
      register: fail2ban_status

    - debug:
        var: fail2ban_status.stdout_lines
