---
- name: Remove and copy fail2ban dingtalk action script
  hosts: ypt
  become: yes

  tasks:
    - name: Check fail2ban status
      command: sudo python3 fail2ban-client status
      register: fail2ban_status

    - debug:
        var: fail2ban_status.stdout_lines
